### ISSUE TITLE
bitmovin API with fMP4

### ISSUE THREAD

**Issue by tysun** [bitmovin/bitdash-demo#2]
With your API is it possible to transcode fMP4 to TS for HLS while at the same time fMP4 is being written? Does one even need a 3rd party API for this?  Apple docs mostly talk about the benefits of fMP4 being with FairPlay and offline usage. You guys are the only ones talking about live streaming.  Thanks

**Comment by msmole** [comment]
Thank you for writing to us and please excuse my delayed response. For support I would propose to write to support@bitmovin.com to get a fast response.

I assume you are talking about our blog post about fMP4:
https://bitmovin.com/hls-news-wwdc-2016/

Would be great if you could let us know your use case at support@bitmovin.com so we can help you better.

Thanks,
Martin
